#!/usr/bin/env python3
"""Generate CineCore_NoLUT.dctl from CineCore.dctl.

Same grading engine, with the LUT film-look stage stripped out, so it compiles
with no luts folder present at all. Generated rather than hand-maintained:
CineCore.dctl stays the single source of truth and this can be re-run after any
change, so the two files cannot drift apart.
"""
import re, sys

src = open('CineCore.dctl', encoding='utf-8').read()
out = src

# 1. drop the two look UI params and the whole LUT declaration block
out = re.sub(r'// ---- Film look -+\n(?:.*\n)*?(?=\n\n// =)', '', out)

# 2. film look becomes a no-op, and the LUT helpers go with it
out = re.sub(r'// A \.cube LUT is only defined across its declared domain.*?\n(?=// =)',
             '', out, flags=re.S)
out = re.sub(r'// ============================================================================\n'
             r'//  SECTION 10 :: FILM LOOK ENGINE\n(?:.*\n)*?'
             r'(?=// ============================================================================\n'
             r'//  SECTION 11 :: OUTPUT SAFETY)', '', out)

# 3. remove the call site
out = out.replace("""    // -- 16. Film look --------------------------------------------------------
    cv = cc_film_look(cv, gLook, gLookMix);

""", "")

# 4. retitle and explain
out = out.replace('//  CineCore\n', '//  CineCore  -  NO LUT BUILD\n', 1)
out = out.replace("""//  ---------------------------------------------------------------------------
//  REQUIRES A LUT FOLDER
//  ---------------------------------------------------------------------------""",
"""//  ---------------------------------------------------------------------------
//  NO LUT FOLDER REQUIRED
//  ---------------------------------------------------------------------------
//  This build has the LUT film-look stage removed, so it compiles on its own
//  with no .cube files present anywhere. Everything else is identical to
//  CineCore.dctl - same grading engine, same controls, same maths.
//
//  Use this if you do not want to manage a luts folder, or as a fallback while
//  sorting one out. Generated by tools/make_nolut.py from CineCore.dctl, so the
//  two cannot drift apart.
//
//  The removed section was:
//  ---------------------------------------------------------------------------""")
out = re.sub(r'//  This DCTL declares LUT files in Section 1 and WILL NOT COMPILE if any of\n'
             r'(?://.*\n)*', '', out)
out = out.replace('SECTION 11 :: OUTPUT SAFETY', 'SECTION 10 :: OUTPUT SAFETY')
out = out.replace('SECTION 12 :: MAIN TRANSFORM', 'SECTION 11 :: MAIN TRANSFORM')
out = out.replace('//                  Look     LUT-based film look selector with mix.\n', '')

assert 'DEFINE_LUT' not in out, "LUT declarations survived the strip"
assert 'APPLY_LUT' not in out, "LUT application survived the strip"
assert 'gLook' not in out, "look params survived the strip"
open('CineCore_NoLUT.dctl', 'w', encoding='utf-8').write(out)
print(f"CineCore_NoLUT.dctl written, {len(out.splitlines())} lines, "
      f"{len(src.splitlines()) - len(out.splitlines())} removed")
